include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude:
    - build/**
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    file_names: false
    public_member_api_docs: false
