name: bff
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bff_api_dto:
    git:
      url: https://github.com/YumNumm/frog_sample.git
      path: packages/bff_api_dto
  dart_frog: ^1.0.0
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  github_api:
    git:
      url: https://github.com/YumNumm/frog_sample.git
      path: packages/github_api
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
