name: bff_api_dto
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.1
  github_api:
    git:
      url: https://github.com/YumNumm/frog_sample.git
      path: packages/github_api
  json_annotation: ^4.8.1
dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^2.0.0
  pedantic_mono: ^1.23.0
  test: ^1.21.0
