name: bff_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  bff_api_dto:
    git:
      url: https://github.com/YumNumm/frog_sample.git
      path: packages/bff_api_dto
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
  retrofit_generator: ^7.0.8
  test: ^1.21.0
